# 모듈과 패키지

In [1]:
# 모듈은 변수, 함수, 클래스를 담고 있는 파일(.py)
# 패키지는 여러 모듈을 묶은 것(폴더)
# import 모듈
# import 모듈1, 모듈2
# 모듈.변수
# 모듈.함수()
# 모듈.클래스()

In [2]:
import math # math라는 모듈
print(math.pi)
print(math.sqrt(4))

3.141592653589793
2.0


In [3]:
import math as m
print(m.pi)
print(m.sqrt(4))

3.141592653589793
2.0


In [4]:
from math import pi, sqrt
print(pi)
print(sqrt(4))

3.141592653589793
2.0


In [5]:
# import 패키지
# import 패키지.모듈1
# import 패키지.모듈1, 패키지.모듈2
# 패키지.모듈.변수
# 패키지.모듈.함수()
# 패키지.모듈.클래스()

In [6]:
import numpy as np # numpy는 라이브러리 (패키지와 모듈을 모아놓음 = 폴더 위에 폴더 )
a = np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
import numpy.random
print(numpy.random.randn(3,3)) # Normal distribution, (3,3)은 3행 3열 짜리를 의미

[[-1.63003804 -0.51679696  0.0266736 ]
 [ 1.39236372 -0.67075841 -1.0299107 ]
 [-0.61751738 -0.15203069  1.34192243]]


In [8]:
import numpy.random as nr
print(nr.randn(3,3))

[[ 0.77320721  0.95871283 -0.2913359 ]
 [ 1.411061   -1.16656165 -0.01095635]
 [-0.06405654 -2.22789689  0.09859238]]


In [9]:
from numpy.random import randn
print(randn(3,3))

[[ 0.17637561 -0.66353113 -0.12262816]
 [ 0.18018203  0.90659489  0.63377039]
 [ 1.54561788  0.53445682  0.40739453]]


# numpy 본격적으로

In [10]:
import numpy as np
a = np.array([1,2,3,4]) # list가 입력으로 들어가는 함수
print(a)
print(type(a))
print(a.dtype)
print(a.shape)
b = np.array([1,2, 3.1, 4])
print(b.dtype) 

[1 2 3 4]
<class 'numpy.ndarray'>
int64
(4,)
float64


In [11]:
A = np.array([[1,2],[3,4]]) # 이셀부터는 import numpy as np 실행했다고 치고 작성
print(A)
print(A.shape) # 자주 쓰임
print(A.ndim) # 차원의 수
print(A.size)

[[1 2]
 [3 4]]
(2, 2)
2
4


In [12]:
print(np.zeros(5))
print(np.zeros_like(A))
print(np.ones(5))
print(np.zeros([3,3]))

print(np.arange(3,10,2) ) # range와 같은데 array로 만들어줌
print(np.arange(0,1, 0.1))
print(np.linspace(0,1,10))
print(np.linspace(0,1,10, endpoint=False)) # 0에서부터 1포함(default) 10개로

[0. 0. 0. 0. 0.]
[[0 0]
 [0 0]]
[1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [13]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a+b
print(c)

[5 7 9]


In [14]:
A = np.array([[1,2,3],[1,2,3]])
B = np.array([[4,5,6],[1,1,1]])
C = A+B
D = A-B
print(C)
print(D)
print(A*B) # 요소와의 곱
print(A/B) # 요소와의 나누기

[[5 7 9]
 [2 3 4]]
[[-3 -3 -3]
 [ 0  1  2]]
[[ 4 10 18]
 [ 1  2  3]]
[[0.25 0.4  0.5 ]
 [1.   2.   3.  ]]


In [15]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,2],[3,4]])
print(A*B)
print(A@B) # 행렬 곱

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


# numpy의 인덱싱과 슬라이싱

In [20]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[0])
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7:])
print(a[:])

1
2
9
[2 3 4]
[8 9]
[1 2 3 4 5 6 7 8 9]


In [28]:
# 행렬에 대한 인덱싱과 슬라이싱
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
print()
print(A[0])
print()
print(A[-1])
print()
print(A[1:])
print()
print(A[0][2])
print()
print(A[0,2])#numpy만 된다.

print(A[0][:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3]

[7 8 9]

[[4 5 6]
 [7 8 9]]

3

3
[1 2 3]


In [40]:
# boolean 인덱싱
a = [1,2,3,4,5,3,3]
print(a == 3) #여러개 값 들어있는 리스트와 3 달랑 하나랑 같냐? 다르다!
A = np.array([[1,2,3,4], [5,3,7,3]])
print(A==3) # 리스트와 달리 각각 요소에 대해 비교해줌
print(A[A==3]) # True, False가 담긴 행렬로 인덱싱 가능!

A[A==3] = 100
print(A)

A = np.array([[1,2], [3,4], [5,6], [7,8]])
B = np.array([True, False, False, True])

print(A[B,:]) #0행, 3행을 슬라이싱

# array 안에 True False 리스트로도 인덱싱 가능
b = np.array([1,2,3,4])
print(b[[True, False, False, True]])
c = [1,2,3,4]
# 리스트 안에 True False 리스트로는 인덱싱은 안됨
# print(c[[True, False, False, True]])

False
[[False False  True False]
 [False  True False  True]]
[3 3 3]
[[  1   2 100   4]
 [  5 100   7 100]]
[[1 2]
 [7 8]]
[1 4]


In [42]:
# 3차원 행렬 인덱싱
A = np.array([ [ [0,1,2,3], [4,5,6,7], [8,9,10,11] ],
               [ [12,13,14,15], [16,17,18,19], [20,21,22,23] ] ])
print(A)
print(A.shape) # 대괄호가 하나 늘어나면 왼쪽 shape값이 추가된다.

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


numpy의 여러 함수들

In [54]:
A = np.random.randn(3,3)
print(A)
print()
B = np.random.rand(3,3)
print(B)
print()
print(A[:,0])
print()
print(A[:,0]<0)
print()
print(A[A[:,0]<0])
print()
print(A[A[:,0]<0,:])

[[ 0.14669371 -1.42127019  0.4430931 ]
 [-0.39444083  0.31280469  0.03066112]
 [ 0.32937717  0.48020589 -1.47347088]]

[[0.26139408 0.02755362 0.60896434]
 [0.90420662 0.97562184 0.57162295]
 [0.54320817 0.58358326 0.1449452 ]]

[ 0.14669371 -0.39444083  0.32937717]

[False  True False]

[[-0.39444083  0.31280469  0.03066112]]

[[-0.39444083  0.31280469  0.03066112]]


In [76]:
A = np.random.randn(3,3)
print(f"A = np.random.randn(3,3) = \n{A}")
print()
print(f"np.abs(A) = \n{np.abs(A)}")
print()
print(f"np.sqrt(np.abs(A)) = \n {np.sqrt(np.abs(A))}")#요소별로 sqrt됨
print()
print(f"np.exp(A) = \n {np.exp(A)}")
print()
print(f"np.log(np.exp(A)) = \n {np.log(np.exp(A))}")
print()
print(f"np.log(np.exp(1)) = \n {np.log(np.exp(1))}") # 자연로그임을 알 수 있다.
print()
print(f"np.log10(10) = \n{np.log10(10)}")
print()
print(f"np.round(A)= \n{np.round(A)}")
print()
print(f"np.round(A,2)=\n{np.round(A,2)}")
print()
print(f"np.floor(A)=\n{np.floor(A)}")
print()
print(f"np.ceil(A)=\n{np.ceil(A)}")


A = np.random.randn(3,3) = 
[[ 1.04874953  0.84013662 -1.27478503]
 [ 0.18778485 -0.38948504  0.79558128]
 [ 0.25613426  1.73194782 -0.86946868]]

np.abs(A) = 
[[1.04874953 0.84013662 1.27478503]
 [0.18778485 0.38948504 0.79558128]
 [0.25613426 1.73194782 0.86946868]]

np.sqrt(np.abs(A)) = 
 [[1.02408473 0.91658967 1.12906378]
 [0.43334149 0.62408736 0.89195363]
 [0.50609708 1.31603488 0.93245305]]

np.exp(A) = 
 [[2.85407995 2.31668346 0.27949104]
 [1.20657389 0.67740562 2.21572858]
 [1.29192617 5.65165158 0.4191742 ]]

np.log(np.exp(A)) = 
 [[ 1.04874953  0.84013662 -1.27478503]
 [ 0.18778485 -0.38948504  0.79558128]
 [ 0.25613426  1.73194782 -0.86946868]]

np.log(np.exp(1)) = 
 1.0

np.log10(10) = 
1.0

np.round(A)= 
[[ 1.  1. -1.]
 [ 0. -0.  1.]
 [ 0.  2. -1.]]

np.round(A,2)=
[[ 1.05  0.84 -1.27]
 [ 0.19 -0.39  0.8 ]
 [ 0.26  1.73 -0.87]]

np.floor(A)=
[[ 1.  0. -2.]
 [ 0. -1.  0.]
 [ 0.  1. -1.]]

np.ceil(A)=
[[ 2.  1. -1.]
 [ 1. -0.  1.]
 [ 1.  2. -0.]]


In [79]:
print(f"np.sin(np.pi/6)=\n{np.sin(np.pi/6)}")
print()
print(f"np.cos(np.pi/3)=\n{np.cos(np.pi/3)}")
print()
print(f"np.tan(np.pi/4)=\n{np.tan(np.pi/4)}")
print()
print(f"np.tanh(-10)=\n{np.tanh(-10)}")

np.sin(np.pi/6)=
0.49999999999999994

np.cos(np.pi/3)=
0.5000000000000001

np.tan(np.pi/4)=
0.9999999999999999

np.tanh(-10)=
-0.9999999958776927








In [84]:
# np.nan # not a number 
#print(f"np.log(-1)=\n{np.log(-1)}")
print(f"np.isnan([1,2,np.nan,3,4])=\n{np.isnan([1,2,np.nan,3,4])}")
print()
print(f"np.isinf([1,2,3,4,np.inf])=\n{np.isinf([1,2,3,4,np.inf])}")

np.isnan([1,2,np.nan,3,4])=
[False False  True False False]
np.isinf([1,2,3,4,np.inf])=
[False False False False  True]


In [ ]:
# 1:07:24