# 모듈과 패키지

In [1]:
# 모듈은 변수, 함수, 클래스를 담고 있는 파일(.py)
# 패키지는 여러 모듈을 묶은 것(폴더)
# import 모듈
# import 모듈1, 모듈2
# 모듈.변수
# 모듈.함수()
# 모듈.클래스()

In [2]:
import math # math라는 모듈
print(math.pi)
print(math.sqrt(4))

3.141592653589793
2.0


In [3]:
import math as m
print(m.pi)
print(m.sqrt(4))

3.141592653589793
2.0


In [4]:
from math import pi, sqrt
print(pi)
print(sqrt(4))

3.141592653589793
2.0


In [5]:
# import 패키지
# import 패키지.모듈1
# import 패키지.모듈1, 패키지.모듈2
# 패키지.모듈.변수
# 패키지.모듈.함수()
# 패키지.모듈.클래스()

In [6]:
import numpy as np # numpy는 라이브러리 (패키지와 모듈을 모아놓음 = 폴더 위에 폴더 )
a = np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
import numpy.random
print(numpy.random.randn(3,3)) # Normal distribution, (3,3)은 3행 3열 짜리를 의미

[[-0.98173899 -1.22262204  0.60579769]
 [-1.13959198 -2.15005285  0.52624557]
 [ 0.06437578 -0.27516525 -2.22072987]]


In [8]:
import numpy.random as nr
print(nr.randn(3,3))

[[-1.85075668 -0.35404116 -2.1330162 ]
 [-1.64701931  0.26955394 -0.33299668]
 [-0.44923168 -0.61259635 -0.79541803]]


In [9]:
from numpy.random import randn
print(randn(3,3))

[[-2.86478469 -1.19674777  0.43329075]
 [-1.24110698 -0.01705039  0.03605127]
 [-1.78299573  1.18079779 -0.54932018]]


# numpy 본격적으로

In [10]:
import numpy as np
a = np.array([1,2,3,4]) # list가 입력으로 들어가는 함수
print(a)
print(type(a))
print(a.dtype)
print(a.shape)
b = np.array([1,2, 3.1, 4])
print(b.dtype) 

[1 2 3 4]
<class 'numpy.ndarray'>
int64
(4,)
float64


In [11]:
A = np.array([[1,2],[3,4]]) # 이셀부터는 import numpy as np 실행했다고 치고 작성
print(A)
print(A.shape) # 자주 쓰임
print(A.ndim) # 차원의 수
print(A.size)

[[1 2]
 [3 4]]
(2, 2)
2
4


In [12]:
print(np.zeros(5))
print(np.zeros_like(A))
print(np.ones(5))
print(np.zeros([3,3]))

print(np.arange(3,10,2) ) # range와 같은데 array로 만들어줌
print(np.arange(0,1, 0.1))
print(np.linspace(0,1,10))
print(np.linspace(0,1,10, endpoint=False)) # 0에서부터 1포함(default) 10개로

[0. 0. 0. 0. 0.]
[[0 0]
 [0 0]]
[1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [13]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a+b
print(c)

[5 7 9]


In [14]:
A = np.array([[1,2,3],[1,2,3]])
B = np.array([[4,5,6],[1,1,1]])
C = A+B
D = A-B
print(C)
print(D)
print(A*B) # 요소와의 곱
print(A/B) # 요소와의 나누기

[[5 7 9]
 [2 3 4]]
[[-3 -3 -3]
 [ 0  1  2]]
[[ 4 10 18]
 [ 1  2  3]]
[[0.25 0.4  0.5 ]
 [1.   2.   3.  ]]


In [15]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,2],[3,4]])
print(A*B)
print(A@B) # 행렬 곱

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


# numpy의 인덱싱과 슬라이싱

In [16]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[0])
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7:])
print(a[:])

1
2
9
[2 3 4]
[8 9]
[1 2 3 4 5 6 7 8 9]


In [17]:
# 행렬에 대한 인덱싱과 슬라이싱
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
print()
print(A[0])
print()
print(A[-1])
print()
print(A[1:])
print()
print(A[0][2])
print()
print(A[0,2])#numpy만 된다.

print(A[0][:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3]

[7 8 9]

[[4 5 6]
 [7 8 9]]

3

3
[1 2 3]


In [18]:
# boolean 인덱싱
a = [1,2,3,4,5,3,3]
print(a == 3) #여러개 값 들어있는 리스트와 3 달랑 하나랑 같냐? 다르다!
A = np.array([[1,2,3,4], [5,3,7,3]])
print(A==3) # 리스트와 달리 각각 요소에 대해 비교해줌
print(A[A==3]) # True, False가 담긴 행렬로 인덱싱 가능!

A[A==3] = 100
print(A)

A = np.array([[1,2], [3,4], [5,6], [7,8]])
B = np.array([True, False, False, True])

print(A[B,:]) #0행, 3행을 슬라이싱

# array 안에 True False 리스트로도 인덱싱 가능
b = np.array([1,2,3,4])
print(b[[True, False, False, True]])
c = [1,2,3,4]
# 리스트 안에 True False 리스트로는 인덱싱은 안됨
# print(c[[True, False, False, True]])

False
[[False False  True False]
 [False  True False  True]]
[3 3 3]
[[  1   2 100   4]
 [  5 100   7 100]]
[[1 2]
 [7 8]]
[1 4]


In [19]:
# 3차원 행렬 인덱싱
A = np.array([ [ [0,1,2,3], [4,5,6,7], [8,9,10,11] ],
               [ [12,13,14,15], [16,17,18,19], [20,21,22,23] ] ])
print(A)
print(A.shape) # 대괄호가 하나 늘어나면 왼쪽 shape값이 추가된다.

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


numpy의 여러 함수들

In [20]:
A = np.random.randn(3,3)
print(A)
print()
B = np.random.rand(3,3)
print(B)
print()
print(A[:,0])
print()
print(A[:,0]<0)
print()
print(A[A[:,0]<0])
print()
print(A[A[:,0]<0,:])

[[ 1.45065343  1.27939781 -1.67924775]
 [-0.89023341 -0.52231089 -0.34007045]
 [ 0.89159326 -0.12612147  0.05317753]]

[[0.58366745 0.96557736 0.81758888]
 [0.63684802 0.64239081 0.88633122]
 [0.23047681 0.62135506 0.17601203]]

[ 1.45065343 -0.89023341  0.89159326]

[False  True False]

[[-0.89023341 -0.52231089 -0.34007045]]

[[-0.89023341 -0.52231089 -0.34007045]]


In [21]:
A = np.random.randn(3,3)
print(f"A = np.random.randn(3,3) = \n{A}")
print()
print(f"np.abs(A) = \n{np.abs(A)}")
print()
print(f"np.sqrt(np.abs(A)) = \n {np.sqrt(np.abs(A))}")#요소별로 sqrt됨
print()
print(f"np.exp(A) = \n {np.exp(A)}")
print()
print(f"np.log(np.exp(A)) = \n {np.log(np.exp(A))}")
print()
print(f"np.log(np.exp(1)) = \n {np.log(np.exp(1))}") # 자연로그임을 알 수 있다.
print()
print(f"np.log10(10) = \n{np.log10(10)}")
print()
print(f"np.round(A)= \n{np.round(A)}")
print()
print(f"np.round(A,2)=\n{np.round(A,2)}")
print()
print(f"np.floor(A)=\n{np.floor(A)}")
print()
print(f"np.ceil(A)=\n{np.ceil(A)}")


A = np.random.randn(3,3) = 
[[ 0.67238778  3.64498089  0.42352087]
 [-0.93169827  2.27147506  0.26602915]
 [-1.19238112  0.39226907  0.26883552]]

np.abs(A) = 
[[0.67238778 3.64498089 0.42352087]
 [0.93169827 2.27147506 0.26602915]
 [1.19238112 0.39226907 0.26883552]]

np.sqrt(np.abs(A)) = 
 [[0.81999255 1.9091833  0.65078481]
 [0.96524519 1.50714135 0.51578014]
 [1.09196205 0.62631388 0.51849351]]

np.exp(A) = 
 [[ 1.95890919 38.28204113  1.52732963]
 [ 0.39388422  9.69368908  1.3047731 ]
 [ 0.30349774  1.48033598  1.30843992]]

np.log(np.exp(A)) = 
 [[ 0.67238778  3.64498089  0.42352087]
 [-0.93169827  2.27147506  0.26602915]
 [-1.19238112  0.39226907  0.26883552]]

np.log(np.exp(1)) = 
 1.0

np.log10(10) = 
1.0

np.round(A)= 
[[ 1.  4.  0.]
 [-1.  2.  0.]
 [-1.  0.  0.]]

np.round(A,2)=
[[ 0.67  3.64  0.42]
 [-0.93  2.27  0.27]
 [-1.19  0.39  0.27]]

np.floor(A)=
[[ 0.  3.  0.]
 [-1.  2.  0.]
 [-2.  0.  0.]]

np.ceil(A)=
[[ 1.  4.  1.]
 [-0.  3.  1.]
 [-1.  1.  1.]]


In [22]:
print(f"np.sin(np.pi/6)=\n{np.sin(np.pi/6)}")
print()
print(f"np.cos(np.pi/3)=\n{np.cos(np.pi/3)}")
print()
print(f"np.tan(np.pi/4)=\n{np.tan(np.pi/4)}")
print()
print(f"np.tanh(-10)=\n{np.tanh(-10)}")

np.sin(np.pi/6)=
0.49999999999999994

np.cos(np.pi/3)=
0.5000000000000001

np.tan(np.pi/4)=
0.9999999999999999

np.tanh(-10)=
-0.9999999958776927


In [23]:
# np.nan # not a number 
#print(f"np.log(-1)=\n{np.log(-1)}")
print(f"np.isnan([1,2,np.nan,3,4])=\n{np.isnan([1,2,np.nan,3,4])}")
print()
print(f"np.isinf([1,2,3,4,np.inf])=\n{np.isinf([1,2,3,4,np.inf])}")

np.isnan([1,2,np.nan,3,4])=
[False False  True False False]

np.isinf([1,2,3,4,np.inf])=
[False False False False  True]


In [24]:
A = np.random.randn(3,4)
print(f"A=\n{A}")
print()
print(f"np.max(A)=\n{np.max(A)}")
print()
print(f"np.max(A,axis=0)=\n{np.max(A,axis=0)}")
print()
print(f"np.max(A,axis=1)=\n{np.max(A,axis=1)}")
print()
print(f"np.max(A,axis=0)=\n{np.max(A,axis=0, keepdims=True)}")
print()
print(f"np.max(A,axis=1)=\n{np.max(A,axis=1, keepdims=True)}")
print()
print(f"A.min(A)=\n{np.min(A)}")
print()
print(f"np.min(A,axis=0)=\n{np.min(A,axis=0, keepdims=True)}")
print()
print(f"np.min(A,axis=1)=\n{np.min(A,axis=1, keepdims=True)}")
print()
print(f"np.argmax(A)=\n{np.argmax(A)}")
print()
print(f"np.argmax(A,axis=0, keepdims=True)=\n{np.argmax(A,axis=0, keepdims=True)}")
print()
print(f"np.argmax(A,axis=1, keepdims=True)=\n{np.argmax(A,axis=1, keepdims=True)}")

A=
[[ 1.52463827 -1.52177292  0.49642149  0.32748369]
 [ 3.0290488  -0.43280153 -1.31979524 -0.31639222]
 [ 0.09043716 -0.15280469 -0.84791921  0.02312179]]

np.max(A)=
3.029048799965116

np.max(A,axis=0)=
[ 3.0290488  -0.15280469  0.49642149  0.32748369]

np.max(A,axis=1)=
[1.52463827 3.0290488  0.09043716]

np.max(A,axis=0)=
[[ 3.0290488  -0.15280469  0.49642149  0.32748369]]

np.max(A,axis=1)=
[[1.52463827]
 [3.0290488 ]
 [0.09043716]]

A.min(A)=
-1.5217729199636196

np.min(A,axis=0)=
[[ 0.09043716 -1.52177292 -1.31979524 -0.31639222]]

np.min(A,axis=1)=
[[-1.52177292]
 [-1.31979524]
 [-0.84791921]]

np.argmax(A)=
4

np.argmax(A,axis=0, keepdims=True)=
[[1 2 0 0]]

np.argmax(A,axis=1, keepdims=True)=
[[0]
 [0]
 [0]]


In [25]:
a = np.random.randn(6,1)
print(f"a=\n{a}\n")
a_sorted_up = np.sort(a,axis = 0)
a_sorted_down = np.flipud(a_sorted_up)
print(f"a_sorted_up=\n{a_sorted_up}\n")
print(f"a_sorted_down=\n{a_sorted_down}\n")

a=
[[ 0.6029599 ]
 [ 0.81333553]
 [ 0.17026771]
 [-1.37565945]
 [-1.22724176]
 [ 0.20522593]]

a_sorted_up=
[[-1.37565945]
 [-1.22724176]
 [ 0.17026771]
 [ 0.20522593]
 [ 0.6029599 ]
 [ 0.81333553]]

a_sorted_down=
[[ 0.81333553]
 [ 0.6029599 ]
 [ 0.20522593]
 [ 0.17026771]
 [-1.22724176]
 [-1.37565945]]



In [26]:
A = np.random.randn(3,4)
print(f"A=\n{A}\n")
print(f"np.sum(A)=\n{np.sum(A)}\n")
print(f"np.sum(A,axis=0, keepdims=True)=\n{np.sum(A,axis=0, keepdims=True)}\n")
print(f"np.sum(A,axis=1, keepdims=True)=\n{np.sum(A,axis=1, keepdims=True)}\n")
print(f"np.mean(A)=\n{np.mean(A)}\n")
print(f"np.mean(A,axis=0, keepdims=True)=\n{np.mean(A,axis=0, keepdims=True)}\n")
print(f"np.mean(A,axis=1, keepdims=True)=\n{np.mean(A,axis=1, keepdims=True)}\n")
print(f"np.std(A)=\n{np.std(A)}\n")
print(f"np.std(A,axis=0, keepdims=True)=\n{np.std(A,axis=0, keepdims=True)}\n")
print(f"np.std(A,axis=1, keepdims=True)=\n{np.std(A,axis=1, keepdims=True)}\n")

A=
[[-0.41623706 -1.13429732  0.84119333  2.21487664]
 [ 1.01041267 -0.43843059  0.4630702  -0.69483536]
 [ 0.79092925 -1.38659766  0.7880458   0.53954132]]

np.sum(A)=
2.5776712072883483

np.sum(A,axis=0, keepdims=True)=
[[ 1.38510486 -2.95932557  2.09230933  2.05958259]]

np.sum(A,axis=1, keepdims=True)=
[[1.50553559]
 [0.34021692]
 [0.7319187 ]]

np.mean(A)=
0.2148059339406957

np.mean(A,axis=0, keepdims=True)=
[[ 0.46170162 -0.98644186  0.69743644  0.68652753]]

np.mean(A,axis=1, keepdims=True)=
[[0.3763839 ]
 [0.08505423]
 [0.18297968]]

np.std(A)=
0.995414397755749

np.std(A,axis=0, keepdims=True)=
[[0.62722962 0.40095813 0.16713631 1.19242322]]

np.std(A,axis=1, keepdims=True)=
[[1.27539299]
 [0.68582951]
 [0.91192337]]



In [27]:
A = np.random.randint(1,5,size=(12,))
print(f"np.random.randint(1,5,size=(12,)=\n{A}\n")
B = A.reshape(2,2,3) # 3차원 행렬
print(f"A.reshape(2,2,3)=\n{A.reshape(2,2,3)}\n")
print(f"B.ndim=\n{B.ndim}\n")

np.random.randint(1,5,size=(12,)=
[2 4 2 2 3 1 4 1 4 3 2 3]

A.reshape(2,2,3)=
[[[2 4 2]
  [2 3 1]]

 [[4 1 4]
  [3 2 3]]]

B.ndim=
3



In [28]:
a = np.array([1,2,3])
b = np.array([2,2,1])

a = a.reshape(3,1)
b = b.reshape(3,1)
print(f"a.transpose()@b=\n{a.transpose()@b}\n")
print(f"a.T@b=\n{a.T@b}\n")

A = np.random.randn(4,3,2)
print(f"np.random.randn(4,3,2).shape=\n{A.shape}\n")
print(f"A.transpose(0,2,1).shape=\n{A.transpose(0,2,1).shape}\n")

a.transpose()@b=
[[9]]

a.T@b=
[[9]]

np.random.randn(4,3,2).shape=
(4, 3, 2)

A.transpose(0,2,1).shape=
(4, 2, 3)



In [29]:
A = np.arange(20)
print(f"A = np.arange(20) = \n{A}\n")

print(f"A.reshape(4,5) = \n{A.reshape(4,5)}\n")
print()
print(f"A.reshape(4,-1) = \n{A.reshape(4,-1)}\n") # 4개 행이 될 수 있도록 열의 수를 맞춰라
# print()


A = np.arange(20) = 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

A.reshape(4,5) = 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


A.reshape(4,-1) = 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]



In [30]:
x1 = np.random.randn(2,3,4,5,6)
print(f"x1 = np.random.randn(2,3,4,5,6) = \n{x1}\n")
print(f"x1.shape = \n{x1.shape}\n")
print(f"x1.ndim = \n{x1.ndim}\n")
print(f"x1[1,2,:,:,:].shape = \n{x1[1,2,:,:,:].shape}\n") 
print(f"x1[1,2,...].shape = \n{x1[1,2,...].shape}\n")# x1[1,2,:,:,:]는 x1[1,2,...]와 같다.


x1 = np.random.randn(2,3,4,5,6) = 
[[[[[ 5.38106847e-01 -1.06881218e-01  1.06068793e+00 -9.57520866e-01
      2.86505904e-01  4.15748149e-01]
    [-1.77672571e+00 -4.49238540e-01 -1.90780469e+00  1.33745357e-01
      4.58319712e-01  6.62363577e-01]
    [-9.90463659e-01  1.31838496e+00 -9.99349457e-01 -1.93325621e+00
     -1.81507588e-01  8.75108976e-01]
    [ 2.08391892e-01  1.15638652e+00  1.28121566e+00  6.10988180e-01
      5.42181453e-01 -5.88482476e-01]
    [ 2.13311475e-01  1.01006937e+00 -3.15585308e-01 -2.45300826e+00
     -2.20581236e-01 -6.18217714e-01]]

   [[ 8.30418640e-01 -1.22442714e+00  7.00275831e-01 -1.25367344e-02
      1.16045697e+00 -1.86100471e-01]
    [-3.81756636e-01  9.18806636e-01 -2.65090124e-02 -6.01379227e-01
     -1.34900507e+00 -1.04357866e+00]
    [-1.61574679e+00  1.21555134e+00 -6.20706196e-01  1.90672921e+00
     -7.11070908e-02 -4.06995894e-02]
    [-1.46692487e+00  7.60868106e-01  5.94141065e-02  3.12567778e+00
      1.42634217e+00 -1.80599029e+00]


In [39]:
A = np.ones((2,2))
B = np.zeros((2,2))
C = np.hstack([A,B])
D = np.vstack([A,B])
E = np.block([A,B])
F = np.block([[A],[B]])
G = np.block([ [[A]], [[B]] ])

print(f"C = np.hstack([A,B]) = \n{C}\n")
print(f"D = np.vstack([A,B]) = \n{D}\n")
print(f"E = np.block([A,B]) = \n{E}\n")
print(f"F = np.block([[A],[B]]) = \n{F}\n")
print(f"G = np.block([ [[A]], [[B]] ]) = \n{G}\n")
print(f"G.shape= \n{G.shape}\n")


C = np.hstack([A,B]) = 
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]

D = np.vstack([A,B]) = 
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]

E = np.block([A,B]) = 
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]

F = np.block([[A],[B]]) = 
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]

G = np.block([ [[A]], [[B]] ]) = 
[[[1. 1.]
  [1. 1.]]

 [[0. 0.]
  [0. 0.]]]

G.shape= 
(2, 2, 2)

np.random.randn(2,3,4) = 
[[[-0.75097436  0.43987725  0.23774715 -1.32767693]
  [ 1.01239266 -0.71858122 -0.17036807  0.97634073]
  [-0.18277527  1.12272676 -1.9027846  -0.99297394]]

 [[ 1.17065493 -0.30957126 -0.42675908 -0.43832867]
  [ 0.15471043 -0.01052617 -1.80555871 -0.60143089]
  [ 1.39160506  0.34015458 -1.37716214 -0.13973612]]]



In [45]:
A = np.random.randn(1,1,1,3,1,1,4,1)
print(f"A.shape = \n{A.shape}\n")
print(f"A.squeeze().shape = \n{A.squeeze().shape}\n")
print(f"A.squeeze(axis=(0,2,4,5)).shape = \n{A.squeeze(axis=(0,2,4,5)).shape}\n")

A.shape = 
(1, 1, 1, 3, 1, 1, 4, 1)

A.squeeze().shape = 
(3, 4)

A.squeeze(axis=(0,2,4,5)).shape = 
(1, 3, 4, 1)



In [51]:
A = np.random.randn(3,4)
A1 = A[np.newaxis,...] # A[np.newaxis,:,:] 와 동일
print(f"A1 = A[np.newaxis,...] = \n {A1} \n")
A2 = A[...,np.newaxis]
print(f"A2 = A[...,np.newaxis] = \n {A2} \n")
A3 = A[:, np.newaxis, :]
print(f"A3 = A[:, np.newaxis, :] = \n {A3} \n")

B1 = np.expand_dims(A,axis=0)
print(f"B1 = np.expand_dims(A,axis=0) = \n {B1} \n")
B2 = np.expand_dims(A,axis=2)
print(f"B2 = np.expand_dims(A,axis=2) = \n {B2} \n")
B3 = np.expand_dims(A,axis=1)
print(f"B3 = np.expand_dims(A,axis=1) = \n {B3} \n")

C1 = A.reshape(1,3,4)
print(f"C1 = A.reshape(1,3,4) = \n {C1} \n")
C2 = A.reshape(3,4,1)
print(f"C2 = A.reshape(3,4,1) = \n {C2} \n")
C3 = A.reshape(3,1,4)
print(f"C3 = A.reshape(3,1,4) = \n {C3} \n")

A1 = A[np.newaxis,...] = 
 [[[-1.31620294 -0.95027981  0.15478468 -2.09079212]
  [-0.69194785 -1.33718232 -0.40088884 -0.68186958]
  [-0.6391676   0.42164456 -0.31326027  0.86342869]]] 

A2 = A[...,np.newaxis] = 
 [[[-1.31620294]
  [-0.95027981]
  [ 0.15478468]
  [-2.09079212]]

 [[-0.69194785]
  [-1.33718232]
  [-0.40088884]
  [-0.68186958]]

 [[-0.6391676 ]
  [ 0.42164456]
  [-0.31326027]
  [ 0.86342869]]] 

A3 = A[:, np.newaxis, :] = 
 [[[-1.31620294 -0.95027981  0.15478468 -2.09079212]]

 [[-0.69194785 -1.33718232 -0.40088884 -0.68186958]]

 [[-0.6391676   0.42164456 -0.31326027  0.86342869]]] 

B1 = np.expand_dims(A,axis=0) = 
 [[[-1.31620294 -0.95027981  0.15478468 -2.09079212]
  [-0.69194785 -1.33718232 -0.40088884 -0.68186958]
  [-0.6391676   0.42164456 -0.31326027  0.86342869]]] 

B2 = np.expand_dims(A,axis=2) = 
 [[[-1.31620294]
  [-0.95027981]
  [ 0.15478468]
  [-2.09079212]]

 [[-0.69194785]
  [-1.33718232]
  [-0.40088884]
  [-0.68186958]]

 [[-0.6391676 ]
  [ 0.42164456]
 