# 모듈과 패키지

In [1]:
# 모듈은 변수, 함수, 클래스를 담고 있는 파일(.py)
# 패키지는 여러 모듈을 묶은 것(폴더)
# import 모듈
# import 모듈1, 모듈2
# 모듈.변수
# 모듈.함수()
# 모듈.클래스()

In [2]:
import math # math라는 모듈
print(math.pi)
print(math.sqrt(4))

3.141592653589793
2.0


In [3]:
import math as m
print(m.pi)
print(m.sqrt(4))

3.141592653589793
2.0


In [4]:
from math import pi, sqrt
print(pi)
print(sqrt(4))

3.141592653589793
2.0


In [5]:
# import 패키지
# import 패키지.모듈1
# import 패키지.모듈1, 패키지.모듈2
# 패키지.모듈.변수
# 패키지.모듈.함수()
# 패키지.모듈.클래스()

In [6]:
import numpy as np # numpy는 라이브러리 (패키지와 모듈을 모아놓음 = 폴더 위에 폴더 )
a = np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
import numpy.random
print(numpy.random.randn(3,3)) # Normal distribution, (3,3)은 3행 3열 짜리를 의미

[[ 1.14792327 -0.00755064 -1.27960707]
 [ 1.41059211 -0.90645243 -0.44850622]
 [-0.53204762  2.08750249 -0.78648512]]


In [8]:
import numpy.random as nr
print(nr.randn(3,3))

[[ 0.48349159  0.8852256   1.06418141]
 [ 0.70696905 -0.89785487 -0.27740363]
 [-0.67957174 -0.38192825  0.05699538]]


In [9]:
from numpy.random import randn
print(randn(3,3))

[[ 0.2986886   0.62025157  0.88745387]
 [-0.67856916  0.61837044  1.02974562]
 [-0.40820964  0.09108111 -0.69970368]]


# numpy 본격적으로

In [10]:
import numpy as np
a = np.array([1,2,3,4]) # list가 입력으로 들어가는 함수
print(a)
print(type(a))
print(a.dtype)
print(a.shape)
b = np.array([1,2, 3.1, 4])
print(b.dtype) 

[1 2 3 4]
<class 'numpy.ndarray'>
int64
(4,)
float64


In [11]:
A = np.array([[1,2],[3,4]]) # 이셀부터는 import numpy as np 실행했다고 치고 작성
print(A)
print(A.shape) # 자주 쓰임
print(A.ndim) # 차원의 수
print(A.size)

[[1 2]
 [3 4]]
(2, 2)
2
4


In [12]:
print(np.zeros(5))
print(np.zeros_like(A))
print(np.ones(5))
print(np.zeros([3,3]))

print(np.arange(3,10,2) ) # range와 같은데 array로 만들어줌
print(np.arange(0,1, 0.1))
print(np.linspace(0,1,10))
print(np.linspace(0,1,10, endpoint=False)) # 0에서부터 1포함(default) 10개로

[0. 0. 0. 0. 0.]
[[0 0]
 [0 0]]
[1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [13]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a+b
print(c)

[5 7 9]


In [14]:
A = np.array([[1,2,3],[1,2,3]])
B = np.array([[4,5,6],[1,1,1]])
C = A+B
D = A-B
print(C)
print(D)
print(A*B) # 요소와의 곱
print(A/B) # 요소와의 나누기

[[5 7 9]
 [2 3 4]]
[[-3 -3 -3]
 [ 0  1  2]]
[[ 4 10 18]
 [ 1  2  3]]
[[0.25 0.4  0.5 ]
 [1.   2.   3.  ]]


In [15]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,2],[3,4]])
print(A*B)
print(A@B) # 행렬 곱

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


# numpy의 인덱싱과 슬라이싱

In [16]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[0])
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7:])
print(a[:])

1
2
9
[2 3 4]
[8 9]
[1 2 3 4 5 6 7 8 9]


In [17]:
# 행렬에 대한 인덱싱과 슬라이싱
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
print()
print(A[0])
print()
print(A[-1])
print()
print(A[1:])
print()
print(A[0][2])
print()
print(A[0,2])#numpy만 된다.

print(A[0][:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3]

[7 8 9]

[[4 5 6]
 [7 8 9]]

3

3
[1 2 3]


In [18]:
# boolean 인덱싱
a = [1,2,3,4,5,3,3]
print(a == 3) #여러개 값 들어있는 리스트와 3 달랑 하나랑 같냐? 다르다!
A = np.array([[1,2,3,4], [5,3,7,3]])
print(A==3) # 리스트와 달리 각각 요소에 대해 비교해줌
print(A[A==3]) # True, False가 담긴 행렬로 인덱싱 가능!

A[A==3] = 100
print(A)

A = np.array([[1,2], [3,4], [5,6], [7,8]])
B = np.array([True, False, False, True])

print(A[B,:]) #0행, 3행을 슬라이싱

# array 안에 True False 리스트로도 인덱싱 가능
b = np.array([1,2,3,4])
print(b[[True, False, False, True]])
c = [1,2,3,4]
# 리스트 안에 True False 리스트로는 인덱싱은 안됨
# print(c[[True, False, False, True]])

False
[[False False  True False]
 [False  True False  True]]
[3 3 3]
[[  1   2 100   4]
 [  5 100   7 100]]
[[1 2]
 [7 8]]
[1 4]


In [19]:
# 3차원 행렬 인덱싱
A = np.array([ [ [0,1,2,3], [4,5,6,7], [8,9,10,11] ],
               [ [12,13,14,15], [16,17,18,19], [20,21,22,23] ] ])
print(A)
print(A.shape) # 대괄호가 하나 늘어나면 왼쪽 shape값이 추가된다.

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


numpy의 여러 함수들

In [20]:
A = np.random.randn(3,3)
print(A)
print()
B = np.random.rand(3,3)
print(B)
print()
print(A[:,0])
print()
print(A[:,0]<0)
print()
print(A[A[:,0]<0])
print()
print(A[A[:,0]<0,:])

[[ 1.47673829 -0.86724272  0.19817442]
 [ 0.36703326 -0.62270044 -0.58897106]
 [ 1.65801782  2.00919302 -3.03347867]]

[[0.8748941  0.05311171 0.90186077]
 [0.77412704 0.7460376  0.44879568]
 [0.22062738 0.61965025 0.5026238 ]]

[1.47673829 0.36703326 1.65801782]

[False False False]

[]

[]


In [21]:
A = np.random.randn(3,3)
print(f"A = np.random.randn(3,3) = \n{A}")
print()
print(f"np.abs(A) = \n{np.abs(A)}")
print()
print(f"np.sqrt(np.abs(A)) = \n {np.sqrt(np.abs(A))}")#요소별로 sqrt됨
print()
print(f"np.exp(A) = \n {np.exp(A)}")
print()
print(f"np.log(np.exp(A)) = \n {np.log(np.exp(A))}")
print()
print(f"np.log(np.exp(1)) = \n {np.log(np.exp(1))}") # 자연로그임을 알 수 있다.
print()
print(f"np.log10(10) = \n{np.log10(10)}")
print()
print(f"np.round(A)= \n{np.round(A)}")
print()
print(f"np.round(A,2)=\n{np.round(A,2)}")
print()
print(f"np.floor(A)=\n{np.floor(A)}")
print()
print(f"np.ceil(A)=\n{np.ceil(A)}")


A = np.random.randn(3,3) = 
[[-0.1014274  -1.6980537   0.73165215]
 [ 0.31031481 -1.13763186  0.12046252]
 [ 0.82420825 -2.28300595 -2.47955606]]

np.abs(A) = 
[[0.1014274  1.6980537  0.73165215]
 [0.31031481 1.13763186 0.12046252]
 [0.82420825 2.28300595 2.47955606]]

np.sqrt(np.abs(A)) = 
 [[0.31847669 1.3030939  0.85536667]
 [0.55705907 1.06659827 0.34707711]
 [0.90785916 1.51096193 1.57466062]]

np.exp(A) = 
 [[0.90354677 0.18303943 2.07851178]
 [1.3638544  0.32057729 1.12801846]
 [2.28007479 0.10197721 0.08378041]]

np.log(np.exp(A)) = 
 [[-0.1014274  -1.6980537   0.73165215]
 [ 0.31031481 -1.13763186  0.12046252]
 [ 0.82420825 -2.28300595 -2.47955606]]

np.log(np.exp(1)) = 
 1.0

np.log10(10) = 
1.0

np.round(A)= 
[[-0. -2.  1.]
 [ 0. -1.  0.]
 [ 1. -2. -2.]]

np.round(A,2)=
[[-0.1  -1.7   0.73]
 [ 0.31 -1.14  0.12]
 [ 0.82 -2.28 -2.48]]

np.floor(A)=
[[-1. -2.  0.]
 [ 0. -2.  0.]
 [ 0. -3. -3.]]

np.ceil(A)=
[[-0. -1.  1.]
 [ 1. -1.  1.]
 [ 1. -2. -2.]]


In [22]:
print(f"np.sin(np.pi/6)=\n{np.sin(np.pi/6)}")
print()
print(f"np.cos(np.pi/3)=\n{np.cos(np.pi/3)}")
print()
print(f"np.tan(np.pi/4)=\n{np.tan(np.pi/4)}")
print()
print(f"np.tanh(-10)=\n{np.tanh(-10)}")

np.sin(np.pi/6)=
0.49999999999999994

np.cos(np.pi/3)=
0.5000000000000001

np.tan(np.pi/4)=
0.9999999999999999

np.tanh(-10)=
-0.9999999958776927


In [23]:
# np.nan # not a number 
#print(f"np.log(-1)=\n{np.log(-1)}")
print(f"np.isnan([1,2,np.nan,3,4])=\n{np.isnan([1,2,np.nan,3,4])}")
print()
print(f"np.isinf([1,2,3,4,np.inf])=\n{np.isinf([1,2,3,4,np.inf])}")

np.isnan([1,2,np.nan,3,4])=
[False False  True False False]

np.isinf([1,2,3,4,np.inf])=
[False False False False  True]


In [40]:
A = np.random.randn(3,4)
print(f"A=\n{A}")
print()
print(f"np.max(A)=\n{np.max(A)}")
print()
print(f"np.max(A,axis=0)=\n{np.max(A,axis=0)}")
print()
print(f"np.max(A,axis=1)=\n{np.max(A,axis=1)}")
print()
print(f"np.max(A,axis=0)=\n{np.max(A,axis=0, keepdims=True)}")
print()
print(f"np.max(A,axis=1)=\n{np.max(A,axis=1, keepdims=True)}")
print()
print(f"A.min(A)=\n{np.min(A)}")
print()
print(f"np.min(A,axis=0)=\n{np.min(A,axis=0, keepdims=True)}")
print()
print(f"np.min(A,axis=1)=\n{np.min(A,axis=1, keepdims=True)}")
print()
print(f"np.argmax(A)=\n{np.argmax(A)}")
print()
print(f"np.argmax(A,axis=0, keepdims=True)=\n{np.argmax(A,axis=0, keepdims=True)}")
print()
print(f"np.argmax(A,axis=1, keepdims=True)=\n{np.argmax(A,axis=1, keepdims=True)}")

A=
[[ 1.127764   -0.93973898 -0.49045424  0.09914107]
 [ 0.90945237 -1.80847031  1.02142705  1.39317253]
 [-0.21199186 -0.02610733 -1.07197457 -0.46187149]]

np.max(A)=
1.3931725292786419

np.max(A,axis=0)=
[ 1.127764   -0.02610733  1.02142705  1.39317253]

np.max(A,axis=1)=
[ 1.127764    1.39317253 -0.02610733]

np.max(A,axis=0)=
[[ 1.127764   -0.02610733  1.02142705  1.39317253]]

np.max(A,axis=1)=
[[ 1.127764  ]
 [ 1.39317253]
 [-0.02610733]]

A.min(A)=
-1.808470312898275

np.min(A,axis=0)=
[[-0.21199186 -1.80847031 -1.07197457 -0.46187149]]

np.min(A,axis=1)=
[[-0.93973898]
 [-1.80847031]
 [-1.07197457]]

np.argmax(A)=
7

np.argmax(A,axis=0, keepdims=True)=
[[0 2 1 1]]

np.argmax(A,axis=1, keepdims=True)=
[[0]
 [3]
 [1]]


In [46]:
a = np.random.randn(6,1)
print(f"a=\n{a}\n")
a_sorted_up = np.sort(a,axis = 0)
a_sorted_down = np.flipud(a_sorted_up)
print(f"a_sorted_up=\n{a_sorted_up}\n")
print(f"a_sorted_down=\n{a_sorted_down}\n")

a=
[[-0.38001506]
 [-0.22798107]
 [ 1.11066119]
 [-1.01675781]
 [-0.12756731]
 [-0.00153315]]

a_sorted_up=
[[-1.01675781]
 [-0.38001506]
 [-0.22798107]
 [-0.12756731]
 [-0.00153315]
 [ 1.11066119]]

a_sorted_down=
[[ 1.11066119]
 [-0.00153315]
 [-0.12756731]
 [-0.22798107]
 [-0.38001506]
 [-1.01675781]]



In [52]:
A = np.random.randn(3,4)
print(f"A=\n{A}\n")
print(f"np.sum(A)=\n{np.sum(A)}\n")
print(f"np.sum(A,axis=0, keepdims=True)=\n{np.sum(A,axis=0, keepdims=True)}\n")
print(f"np.sum(A,axis=1, keepdims=True)=\n{np.sum(A,axis=1, keepdims=True)}\n")
print(f"np.mean(A)=\n{np.mean(A)}\n")
print(f"np.mean(A,axis=0, keepdims=True)=\n{np.mean(A,axis=0, keepdims=True)}\n")
print(f"np.mean(A,axis=1, keepdims=True)=\n{np.mean(A,axis=1, keepdims=True)}\n")
print(f"np.std(A)=\n{np.std(A)}\n")
print(f"np.std(A,axis=0, keepdims=True)=\n{np.std(A,axis=0, keepdims=True)}\n")
print(f"np.std(A,axis=1, keepdims=True)=\n{np.std(A,axis=1, keepdims=True)}\n")

A=
[[ 0.55003464  0.25390344  0.70274934  2.55090631]
 [-0.32842446 -1.43183129  0.08729054 -0.3403688 ]
 [-0.50249193 -0.18162016  1.00309709  2.7755822 ]]

np.sum(A)=
5.138826915411894

np.sum(A,axis=0, keepdims=True)=
[[-0.28088175 -1.35954801  1.79313697  4.98611971]]

np.sum(A,axis=1, keepdims=True)=
[[ 4.05759373]
 [-2.01333401]
 [ 3.0945672 ]]

np.mean(A)=
0.42823557628432446

np.mean(A,axis=0, keepdims=True)=
[[-0.09362725 -0.45318267  0.59771232  1.6620399 ]]

np.mean(A,axis=1, keepdims=True)=
[[ 1.01439843]
 [-0.5033335 ]
 [ 0.7736418 ]]

np.std(A)=
1.1706257064876697

np.std(A,axis=0, keepdims=True)=
[[0.46065196 0.71448585 0.38118236 1.4188846 ]]

np.std(A,axis=1, keepdims=True)=
[[0.90166069]
 [0.56304875]
 [1.28466511]]



In [57]:
A = np.random.randint(1,5,size=(12,))
print(f"np.random.randint(1,5,size=(12,)=\n{A}\n")
B = A.reshape(2,2,3) # 3차원 행렬
print(f"A.reshape(2,2,3)=\n{A.reshape(2,2,3)}\n")
print(f"B.ndim=\n{B.ndim}\n")

np.random.randint(1,5,size=(12,)=
[4 4 2 4 2 3 2 2 2 4 2 1]

A.reshape(2,2,3)=
[[[4 4 2]
  [4 2 3]]

 [[2 2 2]
  [4 2 1]]]

B.ndim=
3



In [64]:
a = np.array([1,2,3])
b = np.array([2,2,1])

a = a.reshape(3,1)
b = b.reshape(3,1)
print(f"a.transpose()@b=\n{a.transpose()@b}\n")
print(f"a.T@b=\n{a.T@b}\n")

A = np.random.randn(4,3,2)
print(f"np.random.randn(4,3,2).shape=\n{A.shape}\n")
print(f"A.transpose(0,2,1).shape=\n{A.transpose(0,2,1).shape}\n")

a.transpose()@b=
[[9]]

a.T@b=
[[9]]

np.random.randn(4,3,2).shape=
(4, 3, 2)

A.transpose(0,2,1).shape=
(4, 2, 3)



In [70]:
A = np.arange(20)
print(f"A = np.arange(20) = \n{A}\n")

print(f"A.reshape(4,5) = \n{A.reshape(4,5)}\n")
print()
print(f"A.reshape(4,-1) = \n{A.reshape(4,-1)}\n") # 4개 행이 될 수 있도록 열의 수를 맞춰라
# print()


A = np.arange(20) = 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

A.reshape(4,5) = 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


A.reshape(4,-1) = 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]



In [71]:
x = np.random.randn(2,3,4,5,6)
print(f"x = np.random.randn(2,3,4,5,6) = \n{x}\n")
print()
# print(f" = \n{}\n")
# print()
# print(f" = \n{}\n")
# print()
# print(f" = \n{}\n")
# print()
# print(f" = \n{}\n")
# print()

x = np.random.randn(2,3,4,5,6) = 
[[[[[-8.64449349e-01  6.25422079e-01  3.68625132e-01  2.01878243e+00
     -2.16592887e-01  9.31143314e-01]
    [-1.28094030e+00  3.82906795e-01 -2.78894686e-01  1.39431133e-01
      7.19169663e-01  1.74385385e+00]
    [ 7.28950485e-01  8.13497564e-01 -5.04835969e-01 -6.47985682e-01
      4.64137950e-01 -7.08092045e-01]
    [ 1.76233477e+00  1.00259685e+00  1.70186654e+00  7.21659363e-01
     -1.77332781e-01 -8.99423974e-01]
    [-4.55251532e-01  2.12334694e+00  1.34353762e+00  2.91999535e-01
      3.11329316e-01  5.89333380e-01]]

   [[-3.90417039e-01 -2.85412196e+00 -2.01653867e-01 -2.44365949e-01
      1.73709813e+00 -8.65063732e-01]
    [-4.20121637e-02  2.53811046e-02  1.73077834e-01  5.14060635e-01
     -1.86438387e+00 -1.46392528e+00]
    [-4.82926340e-01  1.85979152e-01  2.93584838e-01 -1.99543255e-01
      3.89605406e-01 -3.27317849e-01]
    [-5.00567580e-01 -1.72891109e+00  9.95931877e-01  1.64880662e-01
     -6.21746908e-01 -1.30400038e+00]
 