# 모듈과 패키지

In [36]:
# 모듈은 변수, 함수, 클래스를 담고 있는 파일(.py)
# 패키지는 여러 모듈을 묶은 것(폴더)
# import 모듈
# import 모듈1, 모듈2
# 모듈.변수
# 모듈.함수()
# 모듈.클래스()

In [37]:
import math # math라는 모듈
print(math.pi)
print(math.sqrt(4))

3.141592653589793
2.0


In [38]:
import math as m
print(m.pi)
print(m.sqrt(4))

3.141592653589793
2.0


In [39]:
from math import pi, sqrt
print(pi)
print(sqrt(4))

3.141592653589793
2.0


In [40]:
# import 패키지
# import 패키지.모듈1
# import 패키지.모듈1, 패키지.모듈2
# 패키지.모듈.변수
# 패키지.모듈.함수()
# 패키지.모듈.클래스()

In [41]:
import numpy as np # numpy는 라이브러리 (패키지와 모듈을 모아놓음 = 폴더 위에 폴더 )
a = np.array([1,2,3])
print(a)

[1 2 3]


In [42]:
import numpy.random
print(numpy.random.randn(3,3)) # Normal distribution, (3,3)은 3행 3열 짜리를 의미

[[-0.96434372  1.2391796   1.33773918]
 [-0.69180487 -0.50574964 -0.76930315]
 [ 0.39349402  0.68525042  0.43381188]]


In [43]:
import numpy.random as nr
print(nr.randn(3,3))

[[-0.66051923 -0.99990784 -0.03534842]
 [ 0.22723547  0.65483918 -1.65658783]
 [-1.17355495  1.52516697  0.41699015]]


In [44]:
from numpy.random import randn
print(randn(3,3))

[[-0.64831221  1.97903636  0.86625854]
 [ 0.89238665  0.13062369  1.45779131]
 [ 0.71663238  1.35928804 -1.39961806]]


# numpy 본격적으로

In [45]:
import numpy as np
a = np.array([1,2,3,4]) # list가 입력으로 들어가는 함수
print(a)
print(type(a))
print(a.dtype)
print(a.shape)
b = np.array([1,2, 3.1, 4])
print(b.dtype) 

[1 2 3 4]
<class 'numpy.ndarray'>
int64
(4,)
float64


In [46]:
A = np.array([[1,2],[3,4]]) # 이셀부터는 import numpy as np 실행했다고 치고 작성
print(A)
print(A.shape) # 자주 쓰임
print(A.ndim) # 차원의 수
print(A.size)

[[1 2]
 [3 4]]
(2, 2)
2
4


In [47]:
print(np.zeros(5))
print(np.zeros_like(A))
print(np.ones(5))
print(np.zeros([3,3]))

print(np.arange(3,10,2) ) # range와 같은데 array로 만들어줌
print(np.arange(0,1, 0.1))
print(np.linspace(0,1,10))
print(np.linspace(0,1,10, endpoint=False)) # 0에서부터 1포함(default) 10개로

[0. 0. 0. 0. 0.]
[[0 0]
 [0 0]]
[1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [49]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a+b
print(c)

[5 7 9]


In [55]:
A = np.array([[1,2,3],[1,2,3]])
B = np.array([[4,5,6],[1,1,1]])
C = A+B
D = A-B
print(C)
print(D)
print(A*B) # 요소와의 곱
print(A/B) # 요소와의 나누기

[[5 7 9]
 [2 3 4]]
[[-3 -3 -3]
 [ 0  1  2]]
[[ 4 10 18]
 [ 1  2  3]]
[[0.25 0.4  0.5 ]
 [1.   2.   3.  ]]


In [56]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,2],[3,4]])
print(A*B)
print(A@B) # 행렬 곱

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


# numpy의 인덱싱과 슬라이싱